#!/bin/bash
#
#---------------------------------------------------------------------------------
# Copyright (c) 2024 Lancaster University
# Written by: Gerard Hand
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#---------------------------------------------------------------------------------
#
# Usage: scrubbing on|off [mute]
#
# This script sets(off)/unsets(on) the OSD flags NOSCRUB and NODEEP_SCRUB.  If scrubbing
# is turned off (flags set) you can optioninally specify "mute".  This will mute the health warning
# OSDMAP_FLAGS
#
if [ "$1" != "on" ] && [ "$1" != "off" ]; then
  echo "Invalid first parameter. Please use 'on' or 'off'."
  exit 1
fi

if [ "$1" == "on" ]; then
  ceph osd unset nodeep-scrub
  ceph osd unset noscrub
elif [ "$1" == "off" ]; then
  ceph osd set nodeep-scrub
  ceph osd set noscrub
  if [ "$2" == "mute" ]; then
    ceph health mute OSDMAP_FLAGS
  fi
fi

