#!/bin/sh
#
# Copyright (c) 2023 Lancaster University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Written by: Gerard Hand
#
if [[ ! -f ~/.clusterconfig ]]; then
    echo "Creating ~/.clusterconfig"
    echo "FS=\"\"" > ~/.clusterconfig
fi

. ~/.clusterconfig

if [[ "$FS" == "" ]]; then
    echo "ERROR: File system not set."
    echo "Edit ~/.clusterconfig and set the FS variable to file system name"
    exit 1
fi

echo "Stopping Ceph...."
echo "- Stopping $FS file system"
ceph fs set gridpp max_mds 1
ceph fs fail gridpp
ceph fs set gridpp joinable false

echo "- Setting Flags"
ceph osd set noout
ceph osd set norecover
ceph osd set norebalance
ceph osd set nobackfill
ceph osd set nodown
ceph osd set pause

sleep 3
ceph status

